/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
static yyconst short int yy_accept[293] =
    {   0,
        0,    0,    0,    0,   60,   58,    2,    3,    1,   58,
       56,   56,   56,   50,   58,   40,   56,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       56,   59,   59,    2,    1,    0,   43,   44,   45,    0,
        0,   50,   50,   50,    0,    0,   42,    0,   40,    0,
        0,    0,    0,    0,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    0,    0,    0,   57,
        0,    0,   46,    0,    0,   50,    0,   50,    0,    0,

        0,   41,    0,    0,    0,    0,    0,   47,    0,    0,
        0,   40,   40,   40,   40,   40,   40,   40,   13,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   19,   40,   40,   40,   21,   40,   40,   40,
       40,   40,   40,   40,   40,   40,    0,    0,    0,    0,
       49,   51,    0,    0,    0,   55,    0,    0,    0,   52,
        0,    0,    0,    0,    0,    0,   40,   40,   40,   40,
       40,    0,   27,   40,   14,   40,   40,   40,   40,   40,
       40,   17,   40,   40,   40,   40,   40,   40,   40,   40,
        0,   34,   40,   40,   40,   23,    7,   40,   40,   40,

        0,    0,   53,    4,    0,    0,    0,   48,    0,   25,
        0,   24,   40,   40,   40,   11,   15,   40,   10,   40,
       40,    8,   40,   40,   40,   40,   40,   40,   40,   40,
       40,    0,   36,   22,   40,    0,   38,    0,   39,   54,
        0,   26,   12,   40,   16,   10,   40,   40,   40,   40,
       40,   40,   40,   20,   40,    0,   33,   40,   40,    9,
       40,   40,   40,   40,   18,   40,   40,    0,   32,   35,
       40,    0,   28,    5,   40,   40,    0,   31,    6,   35,
       40,   40,   40,   40,   40,   29,    0,   37,   40,    0,
       30,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    4,    1,    5,    6,
        7,    8,    9,    8,    9,   10,    8,   11,   11,   12,
       11,   11,   11,   11,   11,   11,   11,    1,    1,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   17,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       18,    1,   19,    8,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,    8,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    1,
        5,    5,    1,    6,    7,    8,    8,    1,    9,    5,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    1,   10
    } ;

static yyconst short int yy_base[316] =
    {   0,
        0,    0,  905,  904,  950, 1119,  947, 1119,    0,   47,
       49, 1119,   42,   45,   56,  919,   93,   40,   46,   48,
       44,   45,   41,   89,   87,   49,   94,  104,   52,   56,
       86, 1119,  877,  922,    0,  118, 1119, 1119, 1119,  132,
      136,  133,  135,  155,  142,  146, 1119,  166,  903,  902,
      907,  186,  234,  282,  135,  107,  153,  151,  225,  137,
      156,  139,  157,  226,  230,  231,   95,  235,  237,   58,
      242,  165,  236,  238,  311,  247,  312,  313,  250,  315,
      314,  316,  249,  258,  317,  318,  342,  346,  872, 1119,
      352,  354, 1119,  360,  362,  359,  362,  366,  383,  385,

      387, 1119,  389,    0,  409,  418,  457, 1119,  423,  505,
      553,  340,  361,  363,  376,  410,  432,  141,  899,  416,
      373,  320,  413,  419,  348,  420,  421,  429,  411,  428,
      423,  449,  898,  454,  460,  458,  897,  480,  385,  544,
      464,  465,  478,  468,  545,  549,  573,  575,  577,  579,
     1119, 1119,  584,  587,  593, 1119,  600,  896,  627, 1119,
      603,  675,  636,  723,  894,  607,  646,  651,  338,  550,
      471,  491, 1119,  591,  885,  592,  598,  604,  623,  631,
      554,  869,  650,  667,  636,  639,  472,  647,  671,  640,
      694, 1119,  672,  696,  683,  866,  815,  695,  715,  742,

      737,  744, 1119, 1119,  792,  771,  747, 1119,  703, 1119,
      749, 1119,  757,  692,  734,  747,  700,  733,  766,  736,
      752,  694,  754,  738,  638,  684,  760,  741,  762,  811,
      768,  813, 1119,  690,  771,  818, 1119,  820, 1119, 1119,
      826, 1119,  594,  764,  563,  806,  805,  642,  813,  817,
      807,  798,  814,  483,  841,  846, 1119,  826,  830,  475,
      851,  835,  836,  842,  427,  863,  839,  871, 1119,  865,
      850,  878, 1119,  379,  843,  859,  885, 1119,  281,  890,
      875,  855,  862,  896,  876,  243,  901, 1119,  906,  908,
     1119, 1119,  926,  936,  945,  952,  956,  964,  973,  981,

      990,  997, 1004, 1011, 1019, 1029, 1038, 1045, 1054, 1061,
     1069, 1079, 1089, 1098, 1108
    } ;

static yyconst short int yy_def[316] =
    {   0,
      292,    1,  293,  293,  292,  292,  292,  292,  294,  292,
      295,  292,  292,  292,  296,  297,  298,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      299,  292,  300,  292,  294,  292,  292,  292,  292,  301,
      302,  292,  292,  292,  292,  303,  292,  304,  297,  297,
      305,  292,  306,  292,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  307,  308,  300,  292,
      309,  292,  292,  302,  302,  292,  292,  292,  310,  292,

      304,  292,  304,  311,  312,  305,  306,  292,  107,  292,
      313,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  314,  292,  308,  308,
      292,  292,  309,  309,  310,  292,  310,  311,  312,  292,
      159,  315,  305,  313,  292,  164,  297,  297,  297,  297,
      297,  292,  292,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      292,  292,  297,  297,  297,  297,  297,  297,  297,  297,

      314,  314,  292,  292,  315,  292,  205,  292,  292,  292,
      292,  292,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  292,  292,  297,  297,  292,  292,  292,  292,  292,
      292,  292,  297,  297,  297,  292,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  292,  292,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  292,  292,  297,
      297,  292,  292,  297,  297,  297,  292,  292,  297,  292,
      297,  297,  297,  297,  297,  297,  292,  292,  297,  292,
      292,    0,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292
    } ;

static yyconst short int yy_nxt[1168] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   12,   12,   13,
       14,   14,   15,   12,    6,   16,   16,   17,   12,    6,
       18,   16,   19,   20,   16,   21,   22,   16,   23,   16,
       16,   24,   16,   16,   16,   25,   16,   26,   27,   28,
       29,   30,   16,   16,   16,   16,   31,   12,   36,   36,
       40,   40,   42,   42,   43,   44,   44,   46,   46,   50,
       50,   45,   55,   50,   50,   50,   58,   50,   50,   45,
       47,   50,   61,   74,   65,   50,   64,   50,   56,   57,
       59,   63,   62,   75,   86,   85,   60,   87,   87,  130,
       37,   38,   39,   51,   52,   52,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   50,   51,   50,   66,
       54,   68,   51,   50,   50,   69,   76,   67,   77,   36,
       36,   70,   78,   50,   71,   72,   50,   73,  127,   79,
       80,   82,   83,   40,   40,  113,   81,   92,   92,   51,
       51,   84,   93,   42,   42,   96,   96,   46,   46,   45,
       97,   45,   98,   98,   50,   95,   50,   45,   50,   45,
       50,   37,   38,   39,   43,   44,   44,  100,  100,  112,
       50,   45,   50,  114,  118,   50,   50,  121,  120,   45,
      102,  119,  174,  115,   50,  103,   51,   52,   52,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,  104,

       51,  105,  105,   51,  132,   51,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,   51,   51,   51,  106,  106,   51,   51,   51,
       51,   51,   51,   51,   50,   50,   51,  104,   51,   50,
       50,   51,  108,  109,   50,   50,   50,   50,  116,  129,
      122,   50,   50,  117,  125,  123,   50,  136,   50,   50,
      126,  124,  128,  134,  139,  133,  131,   50,  144,  143,
       51,   51,   51,  110,  110,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,  104,   51,  111,  111,   51,

       50,   51,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,   51,   51,
       50,   50,   50,   50,   50,   50,   50,   50,  141,   50,
      142,  177,  146,   87,   87,  145,  138,  148,  148,  213,
      135,  137,  140,   92,   92,   92,   92,   50,  152,   50,
      152,   92,   92,  292,  292,  150,   93,   50,  292,   96,
       96,  154,   98,   98,  180,   45,   98,   98,  167,   95,
       50,   95,   50,   45,  100,  100,  100,  100,  100,  100,
      292,  292,   50,  151,  168,   50,  169,  156,   50,  156,

      170,  102,  157,  292,   50,  176,  103,  193,  103,   51,
      106,  106,   51,   51,   51,   51,   51,   51,   51,  106,
      106,   51,  104,   51,   51,   51,   51,  160,  161,   50,
       50,  104,   50,  172,  172,   50,  160,  173,   50,   50,
       50,  292,   50,  179,  181,  182,   50,   50,   50,  171,
      184,   50,  186,  178,  175,   51,   51,   51,  106,  106,
       51,   51,   51,   51,   51,   51,   51,  183,   50,   51,
      104,   51,  185,   50,   51,  108,  109,   50,  188,   50,
      189,  191,  191,   50,   50,  192,  187,   50,  195,  190,
       50,   50,  172,  172,   50,  215,  173,   50,  196,   50,

      227,  198,   50,   51,   51,   51,  110,  110,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,  104,   51,
      162,  162,   51,  197,   51,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,   51,   51,   51,  163,  163,   51,   51,   51,   51,
       51,   51,   51,   50,   50,   51,  104,   51,   50,   50,
       51,  165,  166,   50,  148,  148,  148,  148,  148,  148,
      292,  292,   50,  194,  199,   92,   92,  214,  292,  292,
      152,  200,  202,  292,  100,  100,  150,  222,  150,   51,

       51,  292,  292,  154,   51,   51,  154,  156,   51,   51,
       50,   50,  157,   50,  292,  216,  217,   50,  218,  157,
      203,  292,  203,   50,  151,  292,  292,   51,  106,  106,
       51,   51,   51,   51,   51,   51,   51,  163,  163,   51,
      104,   51,   50,  219,   51,  160,  161,  209,  209,  104,
       50,  210,  211,  211,  206,   50,  212,   50,   50,   50,
      220,   50,  225,  226,  230,   50,   50,  228,  262,   50,
       50,  221,  251,   51,   51,   51,  163,  163,   51,   51,
       51,   51,   51,   51,   51,  223,   50,   51,  104,   51,
       50,   50,   51,  206,  207,  191,  191,  232,  232,  192,

      231,  233,   50,   50,  209,  209,  252,  224,  210,   50,
      229,   50,  243,   50,   50,   50,  236,  236,  234,   50,
      237,   51,   51,   51,  163,  163,   51,   51,   51,   51,
       51,   51,   51,  235,   50,   51,  104,   51,  148,  148,
       51,  165,  166,  238,  238,  292,  292,  239,   51,   51,
      211,  211,   50,   50,  212,   50,  202,   50,  241,  241,
       50,   50,  242,  202,  245,  292,   50,  246,  246,   51,
       51,   50,  248,   50,  247,  250,   50,  244,  249,   50,
      254,   50,  253,   50,  203,   50,  255,   50,  258,  240,
       50,  292,   51,  163,  163,   51,   51,   51,   51,   51,

       51,   51,  259,  260,   51,  104,   51,  246,  246,   51,
      206,  207,  256,  256,  232,  232,  257,   50,  233,  236,
      236,  238,  238,  237,   50,  239,   50,  241,  241,  261,
       50,  242,   50,   50,   50,  263,   50,  266,   51,   51,
      265,  264,  268,  268,  267,   50,  269,  256,  256,   50,
      271,  257,  272,  272,   50,   50,  273,  270,   50,  274,
       50,   50,   50,  276,  277,  277,  280,  280,  278,   50,
       50,  282,  268,  268,   50,  275,  269,  279,   50,  272,
      272,   50,   50,  273,   50,   50,  277,  277,   50,  281,
      278,  280,  280,  283,   50,   50,  285,  287,  287,  284,

      289,  288,  287,  287,   50,  286,  288,  290,  290,  290,
      290,  291,  208,  291,  204,   50,   50,   50,   50,   90,
      104,   50,   50,   34,   90,   50,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   35,   35,   50,   35,
       35,   35,   35,   35,   35,   35,   41,   41,   34,  292,
       33,   33,   41,   48,   48,  292,  292,  292,   48,   48,
       49,  292,  292,   49,   53,   53,   53,   53,   53,  292,
       53,   53,  292,   53,   88,   88,  292,  292,  292,  292,
       88,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   91,   91,  292,  292,  292,  292,   91,   94,   94,

       94,   94,  292,  292,   94,   99,   99,  292,  292,  292,
      292,   99,  101,  101,  292,  101,  292,  101,  101,   51,
       51,   51,   51,   51,   51,   51,   51,  292,   51,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  147,
      147,  292,  292,  292,  292,  147,  149,  149,  292,  149,
      292,  292,  149,  292,  149,  153,  153,  153,  153,  292,
      292,  153,  155,  155,  292,  155,  292,  155,  155,  158,
      158,  158,  158,  158,  158,  158,  158,  292,  158,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  201,

      201,  292,  201,  292,  292,  201,  292,  201,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,    5,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292
    } ;

static yyconst short int yy_chk[1168] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   10,   10,
       11,   11,   13,   13,   14,   14,   14,   15,   15,   18,
       23,   14,   18,   21,   22,   19,   19,   20,   26,   14,
       15,   29,   20,   26,   23,   30,   22,   70,   18,   18,
       19,   21,   20,   26,   30,   29,   19,   31,   31,   70,
       10,   10,   10,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   25,   17,   24,   24,
       17,   25,   17,   27,   67,   25,   27,   24,   27,   36,
       36,   25,   27,   28,   25,   25,   56,   25,   67,   27,
       27,   28,   28,   40,   40,   56,   27,   41,   41,   17,
       17,   28,   41,   42,   42,   43,   43,   46,   46,   42,
       45,   43,   45,   45,   55,   41,   60,   42,   62,   43,
      118,   36,   36,   36,   44,   44,   44,   48,   48,   55,
       58,   44,   57,   57,   60,   61,   63,   63,   62,   44,
       48,   61,  118,   58,   72,   48,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   72,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   59,   64,   53,   53,   53,   65,
       66,   53,   53,   53,   68,   73,   69,   74,   59,   69,
       64,   71,  286,   59,   66,   65,   76,   76,   83,   79,
       66,   65,   68,   74,   79,   73,   71,   84,   84,   83,
       53,   53,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,

      279,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       75,   77,   78,   81,   80,   82,   85,   86,   81,  122,
       82,  122,   86,   87,   87,   85,   78,   88,   88,  169,
       75,   77,   80,   91,   91,   92,   92,  169,   91,  112,
       92,   94,   94,   95,   95,   88,   94,  125,   95,   96,
       96,   91,   97,   97,  125,   96,   98,   98,  112,   94,
      113,   95,  114,   96,   99,   99,  100,  100,  101,  101,
      103,  103,  121,   88,  113,  115,  114,   99,  274,  100,

      115,  101,   99,  103,  139,  121,  101,  139,  103,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  106,
      106,  105,  105,  105,  109,  109,  105,  105,  105,  116,
      129,  106,  123,  117,  117,  120,  106,  117,  124,  126,
      127,  109,  131,  124,  126,  127,  265,  130,  128,  116,
      129,  117,  131,  123,  120,  105,  105,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  128,  132,  107,
      107,  107,  130,  134,  107,  107,  107,  136,  134,  135,
      135,  138,  138,  141,  142,  138,  132,  144,  141,  136,
      171,  187,  172,  172,  260,  171,  172,  143,  142,  138,

      187,  144,  254,  107,  107,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  143,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  140,  145,  111,  111,  111,  146,  170,
      111,  111,  111,  181,  147,  147,  148,  148,  149,  149,
      150,  150,  245,  140,  145,  153,  153,  170,  154,  154,
      153,  146,  147,  154,  155,  155,  149,  181,  150,  111,

      111,  157,  157,  153,  161,  161,  154,  155,  166,  166,
      174,  176,  155,  243,  157,  174,  176,  177,  177,  157,
      147,  161,  148,  178,  149,  166,  150,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  163,  163,  159,
      159,  159,  179,  178,  159,  159,  159,  167,  167,  163,
      180,  167,  168,  168,  163,  185,  168,  225,  186,  190,
      179,  248,  185,  186,  190,  167,  188,  188,  248,  183,
      168,  180,  225,  159,  159,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  183,  184,  162,  162,  162,
      189,  193,  162,  162,  162,  191,  191,  194,  194,  191,

      193,  194,  195,  226,  209,  209,  226,  184,  209,  234,
      189,  214,  214,  222,  198,  194,  199,  199,  195,  217,
      199,  162,  162,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  198,  199,  164,  164,  164,  201,  201,
      164,  164,  164,  200,  200,  202,  202,  200,  207,  207,
      211,  211,  218,  215,  211,  220,  201,  224,  213,  213,
      228,  200,  213,  202,  218,  207,  216,  219,  219,  164,
      164,  221,  221,  223,  220,  224,  213,  215,  223,  227,
      228,  229,  227,  244,  201,  219,  229,  231,  231,  206,
      235,  202,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  235,  244,  205,  205,  205,  246,  246,  205,
      205,  205,  230,  230,  232,  232,  230,  252,  232,  236,
      236,  238,  238,  236,  247,  238,  251,  241,  241,  247,
      230,  241,  249,  253,  197,  249,  250,  252,  205,  205,
      251,  250,  255,  255,  253,  258,  255,  256,  256,  259,
      259,  256,  261,  261,  262,  263,  261,  258,  267,  262,
      255,  264,  275,  264,  266,  266,  270,  270,  266,  271,
      261,  275,  268,  268,  282,  263,  268,  267,  276,  272,
      272,  283,  266,  272,  270,  196,  277,  277,  182,  271,
      277,  280,  280,  276,  281,  285,  282,  284,  284,  281,

      285,  284,  287,  287,  175,  283,  287,  289,  289,  290,
      290,  289,  165,  290,  158,  284,  137,  133,  119,   89,
       51,   50,   49,   34,   33,  289,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  294,  294,   16,  294,
      294,  294,  294,  294,  294,  294,  295,  295,    7,    5,
        4,    3,  295,  296,  296,    0,    0,    0,  296,  296,
      297,    0,    0,  297,  298,  298,  298,  298,  298,    0,
      298,  298,    0,  298,  299,  299,    0,    0,    0,    0,
      299,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  301,  301,    0,    0,    0,    0,  301,  302,  302,

      302,  302,    0,    0,  302,  303,  303,    0,    0,    0,
        0,  303,  304,  304,    0,  304,    0,  304,  304,  305,
      305,  305,  305,  305,  305,  305,  305,    0,  305,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  307,
      307,    0,    0,    0,    0,  307,  308,  308,    0,  308,
        0,    0,  308,    0,  308,  309,  309,  309,  309,    0,
        0,  309,  310,  310,    0,  310,    0,  310,  310,  311,
      311,  311,  311,  311,  311,  311,  311,    0,  311,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  314,

      314,    0,  314,    0,    0,  314,    0,  314,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sketch.l"
#define INITIAL 0
#line 2 "sketch.l"

/* sketch.l
   Copyright (C) 2005,2006,2007,2008 Eugene K. Ressler, Jr.

This file is part of Sketch, a small, simple system for making 
3d drawings with LaTeX and the PSTricks or TikZ package.

Sketch is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

Sketch is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Sketch; see the file COPYING.txt.  If not, see
http://www.gnu.org/copyleft */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "geometry.h"
#include "symbol.h"
#include "expr.h"
#include "parse.h"
#include "y.tab.h"
#include "error.h"
#include "opts.h"

#if defined(_WIN32) && !defined fileno
#define fileno(F) _fileno(F)
#pragma warning(disable:4102)
#endif

// undo the safety net in polygon.h so flex scanner can use these library functions
#undef malloc
#undef realloc
#undef free
#undef strdup

SRC_LINE line;

#define MAX_INPUT_DEPTH 10

struct {
 YY_BUFFER_STATE buffer_state;
 SRC_LINE line;
} input_stack[MAX_INPUT_DEPTH];
int input_stack_ptr = 0;

#define INIT_SPECIAL_BUF_SIZE 40

void update_line_number(void)
{
  int i;

  for (i = 0; yytext[i]; i++)
    if (yytext[i] == '\n')
      line.number++;
}

#define inputdirective 1

#line 788 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 74 "sketch.l"


#line 942 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 293 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1119 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "sketch.l"
/* comment; do nothing */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "sketch.l"
/* white space; do nothing */ 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "sketch.l"
{ 
  line.number++; 
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "sketch.l"
{ /* [<stuff>=<stuff>] */
  // elide the brackets
  yylval.str = safe_malloc(yyleng + 1 - 2);
  str_slice(yylval.str, yyleng + 1 - 2, yytext, 1, -1);
  return OPTS_STR;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "sketch.l"
{
	return LANGUAGE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "sketch.l"
{
	return PSTRICKS;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "sketch.l"
{
	return TIKZ;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "sketch.l"
{
        return LaTeX;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "sketch.l"
{
        return ConTeXt;
} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 111 "sketch.l"
{
  update_line_number();
  BEGIN(inputdirective);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 116 "sketch.l"
{
  return CURVE;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 120 "sketch.l"
{
  return CAMERA;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "sketch.l"
{
  return DEF;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "sketch.l"
{
  return DOTS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 132 "sketch.l"
{
  return FRAME;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "sketch.l"
{
  return GLOBAL;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "sketch.l"
{
  return LINE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "sketch.l"
{
  return POLYGON;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 148 "sketch.l"
{
  return PUT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 152 "sketch.l"
{
  return REPEAT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 156 "sketch.l"
{
  return SET;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 160 "sketch.l"
{
  return SWEEP;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 164 "sketch.l"
{
  return THEN;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 168 "sketch.l"
{
  update_line_number();
  return ASIN;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 "sketch.l"
{
  update_line_number();
  return ACOS;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 178 "sketch.l"
{
  update_line_number();
  return ATAN2;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 183 "sketch.l"
{
  update_line_number();
  return COS;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 188 "sketch.l"
{
  update_line_number();
  return INVERSE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 193 "sketch.l"
{
  return PICTUREBOX;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 197 "sketch.l"
{
  update_line_number();
  return PERSPECTIVE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 202 "sketch.l"
{
  update_line_number();
  return PROJECT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 207 "sketch.l"
{
  update_line_number();
  return ROTATE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 212 "sketch.l"
{
  update_line_number();
  return SCALE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 217 "sketch.l"
{
  update_line_number();
  return SIN;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 222 "sketch.l"
{  
  char *rtn;
  int max_rtn_len, delim, i, ch;

  update_line_number();

  max_rtn_len = INIT_SPECIAL_BUF_SIZE - 1;
  rtn = safe_malloc(max_rtn_len + 1);
  i = 0;

  delim = input();

  if (delim == EOF) {
    err(line, "expected special text, found end of file");
  }
  else {
    while ((ch = input()) != delim && ch != EOF) {
      if (ch == '\n')
        ++line.number;
      if (i == max_rtn_len) {
        max_rtn_len *= 2;
        rtn = safe_realloc(rtn, max_rtn_len + 1);
      }
      rtn[i++] = ch;
    }
    if (ch != delim)
      err(line, "missing end delimeter '%c' in special", delim);
  }
  rtn[i] = '\0';
  yylval.str = rtn;
  return SPECIAL;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 255 "sketch.l"
{
  update_line_number();
  return SQRT;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 260 "sketch.l"
{
  update_line_number();
  return TRANSLATE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 265 "sketch.l"
{
  update_line_number();
  return UNIT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 270 "sketch.l"
{
  update_line_number();
  return VIEW;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 275 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 0, sizeof yylval.name);
  return ID; 
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 280 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 1, -1);
  return ANGLE_ID; 
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 285 "sketch.l"
{
  return EMPTY_ANGLE;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 289 "sketch.l"
{
  update_line_number();
  yylval.index = 0;
  return TICK;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 295 "sketch.l"
{
  update_line_number();
  yylval.index = 1;
  return TICK;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 301 "sketch.l"
{
  update_line_number();
  yylval.index = 2;
  return TICK;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 307 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 1, -1);
  return PAREN_ID; 
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 312 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 1, -1);
  return BRACKET_ID; 
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 317 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 2, -2);
  return DBL_BRACKET_ID; 
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 322 "sketch.l"
{ 
  str_slice(yylval.name, sizeof yylval.name, yytext, 1, -1);
  return CURLY_ID; 
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 327 "sketch.l"
{ 
  if (sscanf(yytext, FLOAT_SCAN_FMT, &yylval.flt) != 1) {
    err(line, "numeric constant %s could not be converted (probably out of range)", yytext);
    yylval.flt = 0;
  }
  return NUM;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 335 "sketch.l"
{
  warn(line, "found parenthesized identifier '%s'; delete space if you meant a point ref", yytext);
  yyless(1);
  return '(';
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 341 "sketch.l"
{
  warn(line, "found id in brackets '%s'; delete space if you meant a vector ref", yytext);
  yyless(1);
  return '[';
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 347 "sketch.l"
{
  warn(line, "found id in braces '%s'; delete space if you meant a drawable ref", yytext);
  yyless(1);
  return '{';
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 353 "sketch.l"
{
  warn(line, "found id in double-brackets '%s'; delete space if you meant a transform ref", yytext);
  yyless(1);
  return '[';
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 359 "sketch.l"
{
  warn(line, "found id in angle-brackets '%s'; delete space if you meant a tag ref", yytext);
  yyless(1);
  return '<';
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 365 "sketch.l"
{ 
  return yytext[0];	
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 369 "sketch.l"
{

  FILE *f;
  char buf[1024];
  int i;

  // Copy path from current sketch source file name, if any.
  i = str_last_occurance(line.file_name, "/\\");
  if (i >= 0) {
    str_slice(buf, sizeof buf, line.file_name, 0, i + 1);
  }
  else {
    buf[0] = '\0';
  }

  i = strlen(buf);
  str_slice(&buf[i], sizeof buf - i, yytext, 1, -1);

  if (input_stack_ptr >= MAX_INPUT_DEPTH) {
    err(line, "inputs nested too deeply (file '%s' ignored)", buf);
  }
  else {
    f = fopen(buf, "r");
    if (f) {
      yyin = f;
      input_stack[input_stack_ptr].buffer_state = YY_CURRENT_BUFFER;
      input_stack[input_stack_ptr].line = line;
      input_stack_ptr++;
      yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
      line.number = 1;
      line.include_p = 1;
      line.file_name = safe_strdup(buf);
    }
    else
      err(line, "can't open input '%s'", buf);
  }
  BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(inputdirective):
#line 408 "sketch.l"
{
  if (input_stack_ptr == 0) {
    yyterminate();
  }
  else {
    yy_delete_buffer(YY_CURRENT_BUFFER);
    // don't free: refs may still exist for def locs in the symbol table
    // safe_free(line.file_name);
    --input_stack_ptr;
    yy_switch_to_buffer(input_stack[input_stack_ptr].buffer_state);
    line = input_stack[input_stack_ptr].line;
  }
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 422 "sketch.l"
{
  die(line, "bad char '%c' (%d)\n", yytext[0], (int)yytext[0]);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 426 "sketch.l"
ECHO;
	YY_BREAK
#line 1557 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 293 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 293 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 292);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 426 "sketch.l"


void set_lexer_file(char *file_name, FILE *f)
{
  line.file_name = safe_strdup(file_name);
  line.include_p = 0;
  line.number = 1;
  yyin = f;
}
